# Generated by Django 3.2 on 2021-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_setupforgotpassword_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupforgotpassword',
            name='transformed_count',
            field=models.IntegerField(default=0),
        ),
    ]
