# Generated by Django 3.2 on 2021-05-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_setupforgotpassword_transformed_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupforgotpassword',
            name='transformed_count',
        ),
    ]
